In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-102394043954421480022799986720768.0000,
                                          0.0000,
         -102394043954421480022799986720768.0000],
        [                                 0.0000,
                                          0.0000,
                                          0.0000],
        [                                 0.0000,
                                          0.0000,
                                          0.0000],
        [                                 0.0000,
                                          0.0000,
                                          0.0000],
        [                                 0.0000,
                                          0.0000,
                                          0.0000]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7203, 0.8087, 0.2857],
        [0.6390, 0.6467, 0.2473],
        [0.9583, 0.1733, 0.2377],
        [0.4963, 0.3846, 0.7256],
        [0.6334, 0.4087, 0.8333]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2763, -0.4415, -0.4620],
        [ 0.3035, -3.3111,  0.4696],
        [ 0.8003, -0.2400, -0.8852],
        [ 0.2323, -0.3871, -1.2408],
        [ 0.0692, -1.6052, -0.1382]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1686,  0.2448, -0.2253],
        [ 0.5421, -2.9356,  1.0891],
        [ 1.5167,  0.5432, -0.0457],
        [ 0.5309, -0.3539, -0.3295],
        [ 1.0556, -1.3149, -0.1289]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.1686,  0.2448, -0.2253],
        [ 0.5421, -2.9356,  1.0891],
        [ 1.5167,  0.5432, -0.0457],
        [ 0.5309, -0.3539, -0.3295],
        [ 1.0556, -1.3149, -0.1289]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1686,  0.2448, -0.2253],
        [ 0.5421, -2.9356,  1.0891],
        [ 1.5167,  0.5432, -0.0457],
        [ 0.5309, -0.3539, -0.3295],
        [ 1.0556, -1.3149, -0.1289]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1686,  0.2448, -0.2253],
        [ 0.5421, -2.9356,  1.0891],
        [ 1.5167,  0.5432, -0.0457],
        [ 0.5309, -0.3539, -0.3295],
        [ 1.0556, -1.3149, -0.1289]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [14]:
print(x[:, 1])
print(y[1,:])

tensor([-0.4415, -3.3111, -0.2400, -0.3871, -1.6052])
tensor([ 0.5421, -2.9356,  1.0891])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
zz = x.view(4,-1)
print(x.size(), y.size(), z.size(), zz.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([4, 4])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0949])
-0.09489201754331589


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [41]:
a.add_(1)
print("a: ", a)
print("b: ", b)
c = a.numpy()
d = a.add(1)
print("c: ",c)
print("d: ",d)
a.add_(1)
print("a: ",a)
print("c: ",c)

a:  tensor([2., 2., 2., 2., 2.])
b:  [2. 2. 2. 2. 2.]
c:  [2. 2. 2. 2. 2.]
d:  tensor([3., 3., 3., 3., 3.])
a:  tensor([3., 3., 3., 3., 3.])
c:  [3. 3. 3. 3. 3.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [42]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [43]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!